#!/usr/bin/env python3
"""Regenerate hermes-agent's dependency lock from upstream's uv.lock.

This is the whole upgrade story for the Python dependency graph. To move to a
new Hermes release you bump HERMES_VERSION/HERMES_COMMIT in
packages/hermes-agent/Makefile and run:

    python3 scripts/sync-deps.py --ref v0.21.0

No hand-maintained dependency tables, no per-package Makefiles.

What it does
------------
1. Checks out upstream hermes-agent at --ref into a cache dir.
2. Reads pyproject.toml (version, requires-python) and uv.lock (the resolved
   graph, with wheel URLs + sha256 for every package).
3. For each build target -- (CPython minor) x (OpenWrt arch) -- walks the
   dependency graph from the hermes-agent root, evaluating PEP 508 environment
   markers for OpenWrt/musl, and picks one wheel per package.
4. Emits generated make fragments that declare every wheel as an OpenWrt
   Download (so hash-verified, offline-build-friendly), plus a JSON audit file.

Wheel selection prefers a pure-python (`*-none-any`) wheel when one exists,
falling back to a musllinux wheel for the target arch. sdists are never used:
building a C/Rust extension inside the SDK would defeat the point.

Exit status is non-zero if any enabled target cannot be fully satisfied.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

try:
    import tomllib  # py3.11+
except ModuleNotFoundError:  # pragma: no cover
    try:
        import tomli as tomllib  # type: ignore
    except ModuleNotFoundError:
        sys.exit(
            "error: need Python 3.11+ (tomllib) or the 'tomli' package.\n"
            "       pip install tomli"
        )

try:
    from packaging.markers import Marker
    from packaging.utils import canonicalize_name
except ModuleNotFoundError:
    sys.exit(
        "error: this script needs the 'packaging' library.\n"
        "       pip install packaging"
    )

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "packages" / "hermes-agent" / "deps"
UPSTREAM_URL = "https://github.com/NousResearch/hermes-agent.git"
ROOT_PKG = "hermes-agent"

GENERATED_BANNER = (
    "# Generated by scripts/sync-deps.py -- DO NOT EDIT.\n"
    "# Regenerate with: python3 scripts/sync-deps.py --ref <upstream-ref>\n"
)

# ---------------------------------------------------------------------------
# Build target matrix
# ---------------------------------------------------------------------------
# OpenWrt's musl is 1.2.x, so both musllinux_1_1 and musllinux_1_2 wheels run.
MAX_MUSL = (1, 2)

# Only arches with complete musllinux wheel coverage are supported. armv7,
# mips*, and riscv64 are missing wheels for ~a dozen native packages
# (cffi, cryptography, pillow, pydantic-core, uvloop, ...), which would each
# need a from-source cross build. Keep this list in sync with
# PKG_ARCH_DEPENDS in packages/hermes-agent/Makefile.
ARCHES = {
    # musllinux platform tag  : PEP 508 platform_machine
    "x86_64": "x86_64",
    "aarch64": "aarch64",
}

# CPython minors to generate for. Upstream requires-python is >=3.11,<3.14;
# OpenWrt 24.10 ships 3.11 and 25.12 ships 3.13, but generating the middle
# version too costs nothing and survives an SDK bump.
PYTHONS = ["3.11", "3.12", "3.13"]


# ---------------------------------------------------------------------------
# uv.lock model
# ---------------------------------------------------------------------------
@dataclass
class Wheel:
    filename: str
    url: str
    sha256: str
    size: int = 0
    pure: bool = False


@dataclass
class Resolved:
    name: str
    version: str
    wheel: Wheel


@dataclass
class TargetReport:
    python: str
    arch: str
    resolved: list[Resolved] = field(default_factory=list)
    gaps: list[tuple[str, str, str]] = field(default_factory=list)


def marker_env(python: str, machine: str) -> dict[str, str]:
    """Environment for evaluating PEP 508 markers on an OpenWrt/musl target."""
    return {
        "python_version": python,
        # Patch level is unknowable here; markers in practice only compare on
        # minor granularity. Use a high patch so `>= 3.11.4` style pins pass.
        "python_full_version": f"{python}.99",
        "implementation_version": f"{python}.99",
        "sys_platform": "linux",
        "platform_system": "Linux",
        "platform_machine": machine,
        # Deliberately not "android": upstream excludes some packages on
        # Android via `'android' not in platform_release`.
        "platform_release": "6.6.0",
        "platform_version": "#0 SMP",
        "os_name": "posix",
        "implementation_name": "cpython",
        "platform_python_implementation": "CPython",
    }


WHEEL_RE = re.compile(
    r"^(?P<name>[^-]+)-(?P<ver>[^-]+)"
    r"(?:-(?P<build>\d[^-]*))?"
    r"-(?P<py>[^-]+)-(?P<abi>[^-]+)-(?P<plat>[^-]+)\.whl$"
)
MUSL_RE = re.compile(r"^musllinux_(\d+)_(\d+)_(?P<arch>.+)$")


def wheel_matches(filename: str, python: str, musl_arch: str) -> tuple[bool, bool]:
    """Return (compatible, is_pure) for a wheel filename against a target."""
    m = WHEEL_RE.match(filename)
    if not m:
        return False, False
    target_minor = int(python.split(".")[1])
    pys = m["py"].split(".")
    abis = m["abi"].split(".")
    plats = m["plat"].split(".")

    def py_ok() -> bool:
        for tag in pys:
            # abi3 wheels are forward compatible from their cp floor upward.
            if "abi3" in abis and tag.startswith("cp3"):
                try:
                    if target_minor >= int(tag[3:]):
                        return True
                except ValueError:
                    pass
            if tag == f"cp3{target_minor}" or tag == f"py3{target_minor}":
                return True
            if tag in ("py3", "py2.py3"):
                return True
        return False

    if not py_ok():
        return False, False

    if "any" in plats:
        return True, True

    for plat in plats:
        mm = MUSL_RE.match(plat)
        if mm and mm["arch"] == musl_arch:
            if (int(mm.group(1)), int(mm.group(2))) <= MAX_MUSL:
                return True, False
    return False, False


def load_lock(path: Path) -> dict[str, list[dict]]:
    with path.open("rb") as fh:
        data = tomllib.load(fh)
    table: dict[str, list[dict]] = {}
    for pkg in data.get("package", []):
        table.setdefault(canonicalize_name(pkg["name"]), []).append(pkg)
    return table


def entry_deps(entry: dict, extras: tuple[str, ...]) -> list[dict]:
    deps = list(entry.get("dependencies", []))
    optional = entry.get("optional-dependencies") or {}
    for extra in extras:
        deps.extend(optional.get(extra, []))
    return deps


def resolve_target(
    table: dict[str, list[dict]], python: str, musl_arch: str, machine: str
) -> TargetReport:
    report = TargetReport(python=python, arch=musl_arch)
    env = marker_env(python, machine)

    root = table.get(canonicalize_name(ROOT_PKG))
    if not root:
        sys.exit(f"error: {ROOT_PKG!r} not found in uv.lock")

    stack = list(entry_deps(root[0], ()))
    picked: dict[str, dict] = {}

    while stack:
        dep = stack.pop()
        name = canonicalize_name(dep["name"])
        marker = dep.get("marker")
        if marker and not Marker(marker).evaluate(env):
            continue
        extras = tuple(sorted(dep.get("extra") or ()))
        candidates = table.get(name)
        if not candidates:
            report.gaps.append((name, "?", "not present in uv.lock"))
            continue
        entry = candidates[0]
        # A name may be pulled in twice with different extras; union them.
        key = name
        if key in picked:
            already = picked[key].get("_extras", ())
            if set(extras) <= set(already):
                continue
            extras = tuple(sorted(set(extras) | set(already)))
        entry = dict(entry)
        entry["_extras"] = extras
        picked[key] = entry
        stack.extend(entry_deps(entry, extras))

    for name, entry in sorted(picked.items()):
        version = entry.get("version", "?")
        pure_pick: Wheel | None = None
        musl_pick: Wheel | None = None
        for w in entry.get("wheels") or []:
            filename = w["url"].rsplit("/", 1)[-1]
            ok, is_pure = wheel_matches(filename, python, musl_arch)
            if not ok:
                continue
            wheel = Wheel(
                filename=filename,
                url=w["url"],
                sha256=w["hash"].split(":", 1)[-1],
                size=w.get("size", 0),
                pure=is_pure,
            )
            if is_pure:
                pure_pick = pure_pick or wheel
            else:
                musl_pick = musl_pick or wheel
        chosen = pure_pick or musl_pick
        if chosen is None:
            have = ", ".join(
                w["url"].rsplit("/", 1)[-1] for w in (entry.get("wheels") or [])
            ) or "sdist only"
            report.gaps.append((name, version, f"no usable wheel ({have})"))
            continue
        report.resolved.append(Resolved(name=name, version=version, wheel=chosen))
    return report


# ---------------------------------------------------------------------------
# Emitters
# ---------------------------------------------------------------------------
def dl_key(name: str) -> str:
    return "wheel-" + re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def render_mk(var: str, wheels: list[Resolved], title: str) -> str:
    out = [GENERATED_BANNER, f"# {title}\n\n"]
    out.append(f"{var} := \\\n")
    out.extend(f"\t{r.wheel.filename} \\\n" for r in wheels)
    out.append("\n")
    for r in wheels:
        base, fname = r.wheel.url.rsplit("/", 1)
        key = dl_key(r.name)
        out.append(
            f"define Download/{key}\n"
            f"  URL:={base}/\n"
            f"  URL_FILE:={fname}\n"
            f"  FILE:={fname}\n"
            f"  HASH:={r.wheel.sha256}\n"
            f"endef\n"
            f"$(eval $(call Download,{key}))\n\n"
        )
    return "".join(out)


def mirror(repo: Path) -> None:
    """Clone the upstream mirror, tolerating GitHub's anonymous rate limit.

    Anonymous git over HTTPS is throttled per source IP, so any shared address
    -- a CI runner, an office NAT -- can be told HTTP 429 for a clone that works
    fine from a laptop. Retrying usually wins; when it does not, the useful
    answer is not a CalledProcessError traceback but the way around it.
    """
    delay = 5
    for attempt in (1, 2, 3):
        print(f"[sync] mirroring {UPSTREAM_URL}"
              + (f" (attempt {attempt})" if attempt > 1 else ""))
        if subprocess.run(
            ["git", "clone", "--mirror", "--quiet", UPSTREAM_URL, str(repo)]
        ).returncode == 0:
            return
        # A failed clone leaves a partial directory that would be mistaken for a
        # warm cache on the next run.
        shutil.rmtree(repo, ignore_errors=True)
        if attempt < 3:
            print(f"[sync] clone failed; retrying in {delay}s")
            time.sleep(delay)
            delay *= 3

    sys.exit(
        f"error: could not clone {UPSTREAM_URL}\n"
        "       If git reported 429, it was rate-limited rather than refused:\n"
        "       anonymous traffic is throttled per source IP. Either retry later,\n"
        "       or check the commit out some other way and pass --source instead\n"
        "       of --ref (this is what CI does, via actions/checkout)."
    )


def checkout(ref: str, cache: Path) -> Path:
    repo = cache / "hermes-agent.git"
    cache.mkdir(parents=True, exist_ok=True)
    if not repo.exists():
        mirror(repo)
    else:
        print("[sync] fetching upstream")
        subprocess.run(
            ["git", "-C", str(repo), "fetch", "--all", "--tags", "--quiet"], check=False
        )

    # A warm cache plus a fetch that failed is the confusing case: the checkout
    # below would report "pathspec did not match", which reads like a bad ref.
    if subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}"],
        stdout=subprocess.DEVNULL,
    ).returncode:
        sys.exit(
            f"error: {ref} is not in the mirror cache at {repo}\n"
            "       the fetch above did not bring it in -- network, or a bad ref"
        )

    work = cache / "worktree"
    if work.exists():
        shutil.rmtree(work)
    subprocess.run(
        ["git", "-C", str(repo), "worktree", "prune"], check=False,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    subprocess.run(
        ["git", "clone", "--quiet", "--shared", "--no-checkout", str(repo), str(work)],
        check=True,
    )
    subprocess.run(["git", "-C", str(work), "checkout", "--quiet", ref], check=True)
    return work


def main() -> int:
    # Every child process here writes straight to fd 2, so a block-buffered
    # stdout would flush our progress lines after their own error output --
    # which is how a CI log comes to show git's 429 *before* the line saying
    # what was being cloned.
    sys.stdout.reconfigure(line_buffering=True)

    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ref", help="upstream git ref (tag/branch/commit) to sync from")
    ap.add_argument("--source", type=Path,
                    help="use an existing upstream checkout instead of cloning")
    ap.add_argument("--cache", type=Path,
                    default=Path(os.environ.get("HERMES_SYNC_CACHE",
                                                Path.home() / ".cache/hermes-openwrt")),
                    help="git mirror cache dir")
    ap.add_argument("--check", action="store_true",
                    help="verify generated files are current; write nothing")
    args = ap.parse_args()

    if args.source:
        src = args.source.resolve()
    elif args.ref:
        src = checkout(args.ref, args.cache.resolve())
    else:
        ap.error("one of --ref or --source is required")

    pyproject = tomllib.loads((src / "pyproject.toml").read_text(encoding="utf-8"))
    version = pyproject["project"]["version"]
    requires_python = pyproject["project"].get("requires-python", "")
    commit = subprocess.run(
        ["git", "-C", str(src), "rev-parse", "HEAD"],
        capture_output=True, text=True,
    ).stdout.strip() or "unknown"

    print(f"[sync] upstream hermes-agent {version} ({commit[:12]})")
    print(f"[sync] requires-python {requires_python}")

    table = load_lock(src / "uv.lock")

    reports: list[TargetReport] = []
    failed = False
    for python in PYTHONS:
        for musl_arch, machine in ARCHES.items():
            rep = resolve_target(table, python, musl_arch, machine)
            reports.append(rep)
            status = "OK" if not rep.gaps else f"{len(rep.gaps)} GAPS"
            npure = sum(1 for r in rep.resolved if r.wheel.pure)
            total = sum(r.wheel.size for r in rep.resolved)
            print(
                f"[sync]   cp{python.replace('.', '')}/{musl_arch:8s} "
                f"{len(rep.resolved):3d} pkgs ({npure} pure, "
                f"{len(rep.resolved) - npure} native) "
                f"{total / 1048576:5.1f} MiB  {status}"
            )
            for name, ver, why in rep.gaps:
                print(f"[sync]     !! {name} {ver}: {why}")
                failed = True

    if failed:
        print("\nerror: some targets cannot be satisfied by prebuilt wheels.",
              file=sys.stderr)
        return 1

    # Pure wheels are identical across every target -> one shared fragment.
    common: dict[str, Resolved] = {}
    variants: dict[tuple[str, str], list[Resolved]] = {}
    for rep in reports:
        native = []
        for r in rep.resolved:
            if r.wheel.pure:
                common[r.name] = r
            else:
                native.append(r)
        variants[(rep.python, rep.arch)] = native

    files: dict[Path, str] = {}
    common_list = [common[k] for k in sorted(common)]
    files[OUT_DIR / "wheels-common.mk"] = render_mk(
        "HERMES_WHEELS_COMMON", common_list,
        "Pure-python wheels: identical for every python version and arch.",
    )
    for (python, arch), native in sorted(variants.items()):
        tag = f"cp{python.replace('.', '')}"
        files[OUT_DIR / f"wheels-{tag}-{arch}.mk"] = render_mk(
            "HERMES_WHEELS_NATIVE", native,
            f"Native-extension wheels for CPython {python} on musl/{arch}.",
        )

    audit = {
        "_comment": "Generated by scripts/sync-deps.py -- do not edit.",
        "upstream": {
            "url": UPSTREAM_URL,
            "version": version,
            "commit": commit,
            "requires_python": requires_python,
        },
        "targets": {
            f"cp{rep.python.replace('.', '')}-{rep.arch}": {
                "python": rep.python,
                "arch": rep.arch,
                "packages": {
                    r.name: {
                        "version": r.version,
                        "wheel": r.wheel.filename,
                        "sha256": r.wheel.sha256,
                        "pure": r.wheel.pure,
                    }
                    for r in sorted(rep.resolved, key=lambda r: r.name)
                },
            }
            for rep in reports
        },
    }
    files[OUT_DIR / "deps.lock.json"] = json.dumps(audit, indent=2,
                                                   sort_keys=False) + "\n"

    if args.check:
        stale = [p for p, body in files.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != body]
        if stale:
            print("\nerror: generated dependency files are out of date:",
                  file=sys.stderr)
            for p in stale:
                print(f"  {p.relative_to(REPO)}", file=sys.stderr)
            print("run: python3 scripts/sync-deps.py --ref <ref>", file=sys.stderr)
            return 1
        print("[sync] generated files are up to date")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for p, body in sorted(files.items()):
        p.write_text(body, encoding="utf-8")
        print(f"[sync] wrote {p.relative_to(REPO)}")

    print(f"\n[sync] done. Set in packages/hermes-agent/Makefile:\n"
          f"         PKG_VERSION:={version}\n"
          f"         PKG_SOURCE_VERSION:={commit}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
